# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adcp_terminal.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdcpTerminal(object):
    def setupUi(self, AdcpTerminal):
        AdcpTerminal.setObjectName("AdcpTerminal")
        AdcpTerminal.resize(1008, 818)
        self.centralWidget = QtWidgets.QWidget(AdcpTerminal)
        self.centralWidget.setObjectName("centralWidget")
        self.terminalText = QtWidgets.QTextEdit(self.centralWidget)
        self.terminalText.setGeometry(QtCore.QRect(30, 30, 481, 501))
        self.terminalText.setLineWrapMode(QtWidgets.QTextEdit.FixedColumnWidth)
        self.terminalText.setLineWrapColumnOrWidth(50)
        self.terminalText.setReadOnly(False)
        self.terminalText.setObjectName("terminalText")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 540, 481, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmdLineText = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.cmdLineText.setObjectName("cmdLineText")
        self.horizontalLayout.addWidget(self.cmdLineText)
        self.sendButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.ensJsonText = QtWidgets.QTextEdit(self.centralWidget)
        self.ensJsonText.setGeometry(QtCore.QRect(520, 30, 251, 501))
        self.ensJsonText.setLineWrapMode(QtWidgets.QTextEdit.FixedColumnWidth)
        self.ensJsonText.setLineWrapColumnOrWidth(75)
        self.ensJsonText.setReadOnly(True)
        self.ensJsonText.setObjectName("ensJsonText")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(790, 30, 191, 141))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialPortcomboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.serialPortcomboBox.setObjectName("serialPortcomboBox")
        self.verticalLayout.addWidget(self.serialPortcomboBox)
        self.baudRatecomboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.baudRatecomboBox.setObjectName("baudRatecomboBox")
        self.verticalLayout.addWidget(self.baudRatecomboBox)
        self.serialConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.serialConnectButton.setObjectName("serialConnectButton")
        self.verticalLayout.addWidget(self.serialConnectButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(790, 170, 191, 381))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 173, 338))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.breakButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.breakButton.setObjectName("breakButton")
        self.verticalLayout_2.addWidget(self.breakButton)
        self.startPingButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.startPingButton.setObjectName("startPingButton")
        self.verticalLayout_2.addWidget(self.startPingButton)
        self.stopPingButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.stopPingButton.setObjectName("stopPingButton")
        self.verticalLayout_2.addWidget(self.stopPingButton)
        self.cshowButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.cshowButton.setObjectName("cshowButton")
        self.verticalLayout_2.addWidget(self.cshowButton)
        self.sleepButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.sleepButton.setObjectName("sleepButton")
        self.verticalLayout_2.addWidget(self.sleepButton)
        self.setTimeButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.setTimeButton.setObjectName("setTimeButton")
        self.verticalLayout_2.addWidget(self.setTimeButton)
        self.cemacButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.cemacButton.setObjectName("cemacButton")
        self.verticalLayout_2.addWidget(self.cemacButton)
        self.zeroPressureSensorButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.zeroPressureSensorButton.setObjectName("zeroPressureSensorButton")
        self.verticalLayout_2.addWidget(self.zeroPressureSensorButton)
        self.compassConnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.compassConnectButton.setObjectName("compassConnectButton")
        self.verticalLayout_2.addWidget(self.compassConnectButton)
        self.compassDisconnectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.compassDisconnectButton.setObjectName("compassDisconnectButton")
        self.verticalLayout_2.addWidget(self.compassDisconnectButton)
        AdcpTerminal.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AdcpTerminal)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1008, 22))
        self.menuBar.setObjectName("menuBar")
        AdcpTerminal.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(AdcpTerminal)
        self.mainToolBar.setObjectName("mainToolBar")
        AdcpTerminal.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(AdcpTerminal)
        self.statusBar.setObjectName("statusBar")
        AdcpTerminal.setStatusBar(self.statusBar)

        self.retranslateUi(AdcpTerminal)
        QtCore.QMetaObject.connectSlotsByName(AdcpTerminal)

    def retranslateUi(self, AdcpTerminal):
        _translate = QtCore.QCoreApplication.translate
        AdcpTerminal.setWindowTitle(_translate("AdcpTerminal", "MainWindow"))
        self.sendButton.setText(_translate("AdcpTerminal", "SEND"))
        self.groupBox.setTitle(_translate("AdcpTerminal", "ADCP"))
        self.serialConnectButton.setText(_translate("AdcpTerminal", "Connect"))
        self.groupBox_2.setTitle(_translate("AdcpTerminal", "Commands"))
        self.breakButton.setText(_translate("AdcpTerminal", "BREAK"))
        self.startPingButton.setText(_translate("AdcpTerminal", "START PING"))
        self.stopPingButton.setText(_translate("AdcpTerminal", "STOP PING"))
        self.cshowButton.setText(_translate("AdcpTerminal", "CSHOW"))
        self.sleepButton.setText(_translate("AdcpTerminal", "SLEEP"))
        self.setTimeButton.setText(_translate("AdcpTerminal", "SET TIME"))
        self.cemacButton.setText(_translate("AdcpTerminal", "CEMAC"))
        self.zeroPressureSensorButton.setText(_translate("AdcpTerminal", "Zero Pressure Sensor"))
        self.compassConnectButton.setText(_translate("AdcpTerminal", "Compass Connect"))
        self.compassDisconnectButton.setText(_translate("AdcpTerminal", "Compass Disconnect"))

