# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subsystem_view.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Subsystem(object):
    def setupUi(self, Subsystem):
        Subsystem.setObjectName("Subsystem")
        Subsystem.resize(709, 826)
        self.groupBox_2 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 30, 311, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 271, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cbtonCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.cbtonCheckBox.setText("")
        self.cbtonCheckBox.setObjectName("cbtonCheckBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbtonCheckBox)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cbtbbComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbtbbComboBox.setObjectName("cbtbbComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbtbbComboBox)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cbttbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.cbttbpDoubleSpinBox.setObjectName("cbttbpDoubleSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbttbpDoubleSpinBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 190, 311, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 281, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cbiEnabledCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.cbiEnabledCheckBox.setText("")
        self.cbiEnabledCheckBox.setObjectName("cbiEnabledCheckBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbiEnabledCheckBox)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cbiBurstIntervalDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.cbiBurstIntervalDoubleSpinBox.setMinimum(0.0)
        self.cbiBurstIntervalDoubleSpinBox.setMaximum(86400.0)
        self.cbiBurstIntervalDoubleSpinBox.setProperty("value", 900.0)
        self.cbiBurstIntervalDoubleSpinBox.setObjectName("cbiBurstIntervalDoubleSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbiBurstIntervalDoubleSpinBox)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.cbiNumEnsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.cbiNumEnsSpinBox.setMaximum(5000)
        self.cbiNumEnsSpinBox.setSingleStep(128)
        self.cbiNumEnsSpinBox.setProperty("value", 2048)
        self.cbiNumEnsSpinBox.setObjectName("cbiNumEnsSpinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbiNumEnsSpinBox)
        self.groupBox = QtWidgets.QGroupBox(Subsystem)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 311, 311))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cwponCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cwponCheckBox.setText("")
        self.cwponCheckBox.setObjectName("cwponCheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cwponCheckBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cwpblDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpblDoubleSpinBox.setSingleStep(0.25)
        self.cwpblDoubleSpinBox.setProperty("value", 0.5)
        self.cwpblDoubleSpinBox.setObjectName("cwpblDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cwpblDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cwpbsDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpbsDoubleSpinBox.setMinimum(0.01)
        self.cwpbsDoubleSpinBox.setMaximum(200.0)
        self.cwpbsDoubleSpinBox.setSingleStep(0.1)
        self.cwpbsDoubleSpinBox.setProperty("value", 1.0)
        self.cwpbsDoubleSpinBox.setObjectName("cwpbsDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cwpbsDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cwpbnSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cwpbnSpinBox.setMinimum(1)
        self.cwpbnSpinBox.setMaximum(200)
        self.cwpbnSpinBox.setProperty("value", 30)
        self.cwpbnSpinBox.setObjectName("cwpbnSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cwpbnSpinBox)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cwpbbDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpbbDoubleSpinBox.setSingleStep(0.1)
        self.cwpbbDoubleSpinBox.setProperty("value", 0.5)
        self.cwpbbDoubleSpinBox.setObjectName("cwpbbDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cwpbbDoubleSpinBox)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cwpbbComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cwpbbComboBox.setObjectName("cwpbbComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cwpbbComboBox)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cwppSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cwppSpinBox.setMaximum(500)
        self.cwppSpinBox.setProperty("value", 1)
        self.cwppSpinBox.setObjectName("cwppSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cwppSpinBox)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cwptbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwptbpDoubleSpinBox.setSingleStep(0.1)
        self.cwptbpDoubleSpinBox.setProperty("value", 0.1)
        self.cwptbpDoubleSpinBox.setObjectName("cwptbpDoubleSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cwptbpDoubleSpinBox)
        self.groupBox_4 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 400, 631, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.cedBeamVelCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedBeamVelCheckBox.setGeometry(QtCore.QRect(10, 30, 86, 20))
        self.cedBeamVelCheckBox.setObjectName("cedBeamVelCheckBox")
        self.cedInstrVelCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedInstrVelCheckBox.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.cedInstrVelCheckBox.setObjectName("cedInstrVelCheckBox")
        self.cedEarthVelCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedEarthVelCheckBox.setGeometry(QtCore.QRect(10, 70, 86, 20))
        self.cedEarthVelCheckBox.setObjectName("cedEarthVelCheckBox")
        self.cedAmpCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedAmpCheckBox.setGeometry(QtCore.QRect(10, 90, 86, 20))
        self.cedAmpCheckBox.setObjectName("cedAmpCheckBox")
        self.cedCorrCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedCorrCheckBox.setGeometry(QtCore.QRect(10, 110, 111, 20))
        self.cedCorrCheckBox.setObjectName("cedCorrCheckBox")
        self.cedBeamGoodPingCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedBeamGoodPingCheckBox.setGeometry(QtCore.QRect(160, 30, 131, 20))
        self.cedBeamGoodPingCheckBox.setObjectName("cedBeamGoodPingCheckBox")
        self.cedEarthGoodPingCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedEarthGoodPingCheckBox.setGeometry(QtCore.QRect(160, 50, 131, 20))
        self.cedEarthGoodPingCheckBox.setObjectName("cedEarthGoodPingCheckBox")
        self.cedEnsCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedEnsCheckBox.setGeometry(QtCore.QRect(160, 70, 86, 20))
        self.cedEnsCheckBox.setObjectName("cedEnsCheckBox")
        self.cedAncCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedAncCheckBox.setGeometry(QtCore.QRect(160, 90, 86, 20))
        self.cedAncCheckBox.setObjectName("cedAncCheckBox")
        self.cedBtCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedBtCheckBox.setGeometry(QtCore.QRect(160, 110, 121, 20))
        self.cedBtCheckBox.setObjectName("cedBtCheckBox")
        self.cedNmeaCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedNmeaCheckBox.setGeometry(QtCore.QRect(310, 30, 86, 20))
        self.cedNmeaCheckBox.setObjectName("cedNmeaCheckBox")
        self.cedWpEngCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedWpEngCheckBox.setGeometry(QtCore.QRect(310, 50, 131, 20))
        self.cedWpEngCheckBox.setObjectName("cedWpEngCheckBox")
        self.cedBtEngCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedBtEngCheckBox.setGeometry(QtCore.QRect(310, 70, 121, 20))
        self.cedBtEngCheckBox.setObjectName("cedBtEngCheckBox")
        self.cedSysSettingCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedSysSettingCheckBox.setGeometry(QtCore.QRect(310, 90, 131, 20))
        self.cedSysSettingCheckBox.setObjectName("cedSysSettingCheckBox")
        self.cedRangeTrackingCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.cedRangeTrackingCheckBox.setGeometry(QtCore.QRect(310, 110, 131, 20))
        self.cedRangeTrackingCheckBox.setObjectName("cedRangeTrackingCheckBox")
        self.groupBox_5 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 550, 631, 251))
        self.groupBox_5.setObjectName("groupBox_5")
        self.widget = QtWidgets.QWidget(self.groupBox_5)
        self.widget.setGeometry(QtCore.QRect(20, 30, 291, 198))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 6, 0, 1, 1)
        self.dataUsageLabel = QtWidgets.QLabel(self.widget)
        self.dataUsageLabel.setText("")
        self.dataUsageLabel.setObjectName("dataUsageLabel")
        self.gridLayout_2.addWidget(self.dataUsageLabel, 7, 1, 1, 1)
        self.numBatteriesLabel = QtWidgets.QLabel(self.widget)
        self.numBatteriesLabel.setText("")
        self.numBatteriesLabel.setObjectName("numBatteriesLabel")
        self.gridLayout_2.addWidget(self.numBatteriesLabel, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 3, 0, 1, 1)
        self.wpRangeLabel = QtWidgets.QLabel(self.widget)
        self.wpRangeLabel.setText("")
        self.wpRangeLabel.setObjectName("wpRangeLabel")
        self.gridLayout_2.addWidget(self.wpRangeLabel, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.powerLabel = QtWidgets.QLabel(self.widget)
        self.powerLabel.setText("")
        self.powerLabel.setObjectName("powerLabel")
        self.gridLayout_2.addWidget(self.powerLabel, 0, 1, 1, 1)
        self.btRangeLabel = QtWidgets.QLabel(self.widget)
        self.btRangeLabel.setText("")
        self.btRangeLabel.setObjectName("btRangeLabel")
        self.gridLayout_2.addWidget(self.btRangeLabel, 6, 1, 1, 1)
        self.maxVelLabel = QtWidgets.QLabel(self.widget)
        self.maxVelLabel.setText("")
        self.maxVelLabel.setObjectName("maxVelLabel")
        self.gridLayout_2.addWidget(self.maxVelLabel, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 5, 0, 1, 1)
        self.stdLabel = QtWidgets.QLabel(self.widget)
        self.stdLabel.setText("")
        self.stdLabel.setObjectName("stdLabel")
        self.gridLayout_2.addWidget(self.stdLabel, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 1)
        self.firstBinPosLabel = QtWidgets.QLabel(self.widget)
        self.firstBinPosLabel.setText("")
        self.firstBinPosLabel.setObjectName("firstBinPosLabel")
        self.gridLayout_2.addWidget(self.firstBinPosLabel, 4, 1, 1, 1)
        self.label_16.raise_()
        self.label_25.raise_()
        self.freqLabel = QtWidgets.QLabel(Subsystem)
        self.freqLabel.setGeometry(QtCore.QRect(260, 10, 211, 16))
        self.freqLabel.setObjectName("freqLabel")
        self.groupBox_6 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 340, 311, 61))
        self.groupBox_6.setObjectName("groupBox_6")
        self.numBeamsSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.numBeamsSpinBox.setGeometry(QtCore.QRect(170, 30, 111, 24))
        self.numBeamsSpinBox.setMinimum(1)
        self.numBeamsSpinBox.setMaximum(4)
        self.numBeamsSpinBox.setProperty("value", 4)
        self.numBeamsSpinBox.setObjectName("numBeamsSpinBox")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(48, 30, 111, 20))
        self.label_15.setObjectName("label_15")

        self.retranslateUi(Subsystem)
        QtCore.QMetaObject.connectSlotsByName(Subsystem)

    def retranslateUi(self, Subsystem):
        _translate = QtCore.QCoreApplication.translate
        Subsystem.setWindowTitle(_translate("Subsystem", "MainWindow"))
        self.groupBox_2.setTitle(_translate("Subsystem", "Bottom Track"))
        self.label_9.setText(_translate("Subsystem", "CBTON"))
        self.label_10.setText(_translate("Subsystem", "CBTBB"))
        self.label_11.setText(_translate("Subsystem", "CBTTBP (s)"))
        self.groupBox_3.setTitle(_translate("Subsystem", "Burst Mode"))
        self.label_12.setText(_translate("Subsystem", "Burst Mode ON"))
        self.label_13.setText(_translate("Subsystem", "Burst Interval (s)"))
        self.label_14.setText(_translate("Subsystem", "Number of Ensembles"))
        self.groupBox.setTitle(_translate("Subsystem", "Water Profile"))
        self.label.setText(_translate("Subsystem", "CWPON"))
        self.label_2.setText(_translate("Subsystem", "CWPBL (m)"))
        self.label_3.setText(_translate("Subsystem", "CWPBS (m)"))
        self.label_4.setText(_translate("Subsystem", "CWPBN (bins)"))
        self.label_5.setText(_translate("Subsystem", "CWPBB Lag Length (m)"))
        self.label_6.setText(_translate("Subsystem", "Pulse Type"))
        self.label_7.setText(_translate("Subsystem", "CWPP (pings)"))
        self.label_8.setText(_translate("Subsystem", "CWPTBP (s)"))
        self.groupBox_4.setTitle(_translate("Subsystem", "Data Output"))
        self.cedBeamVelCheckBox.setText(_translate("Subsystem", "Beam Vel"))
        self.cedInstrVelCheckBox.setText(_translate("Subsystem", "Instrument Vel"))
        self.cedEarthVelCheckBox.setText(_translate("Subsystem", "Earth Vel"))
        self.cedAmpCheckBox.setText(_translate("Subsystem", "Amplitude"))
        self.cedCorrCheckBox.setText(_translate("Subsystem", "Correlation"))
        self.cedBeamGoodPingCheckBox.setText(_translate("Subsystem", "Beam Good Ping"))
        self.cedEarthGoodPingCheckBox.setText(_translate("Subsystem", "Earth Good Ping"))
        self.cedEnsCheckBox.setText(_translate("Subsystem", "Ensemble"))
        self.cedAncCheckBox.setText(_translate("Subsystem", "Ancillary"))
        self.cedBtCheckBox.setText(_translate("Subsystem", "Bottom Track"))
        self.cedNmeaCheckBox.setText(_translate("Subsystem", "NMEA"))
        self.cedWpEngCheckBox.setText(_translate("Subsystem", "WP Engineering"))
        self.cedBtEngCheckBox.setText(_translate("Subsystem", "BT Engineering"))
        self.cedSysSettingCheckBox.setText(_translate("Subsystem", "System Settings"))
        self.cedRangeTrackingCheckBox.setText(_translate("Subsystem", "Range Tracking"))
        self.groupBox_5.setTitle(_translate("Subsystem", "Predictions"))
        self.label_27.setText(_translate("Subsystem", "Bottom Track Range: "))
        self.label_17.setText(_translate("Subsystem", "Num Batteries: "))
        self.label_21.setText(_translate("Subsystem", "Standard Deviation: "))
        self.label_19.setText(_translate("Subsystem", "Maximum Velocity: "))
        self.label_16.setText(_translate("Subsystem", "Power Usage: "))
        self.label_25.setText(_translate("Subsystem", "Water Profile Range: "))
        self.label_29.setText(_translate("Subsystem", "Data Usage: "))
        self.label_23.setText(_translate("Subsystem", "First Bin Position: "))
        self.freqLabel.setText(_translate("Subsystem", "TextLabel"))
        self.groupBox_6.setTitle(_translate("Subsystem", "Beams"))
        self.label_15.setText(_translate("Subsystem", "Number of Beams"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Subsystem = QtWidgets.QWidget()
    ui = Ui_Subsystem()
    ui.setupUi(Subsystem)
    Subsystem.show()
    sys.exit(app.exec_())

