# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subsystem_view.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Subsystem(object):
    def setupUi(self, Subsystem):
        Subsystem.setObjectName("Subsystem")
        Subsystem.resize(709, 757)
        self.groupBox_2 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 10, 311, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 271, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cbtonCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.cbtonCheckBox.setText("")
        self.cbtonCheckBox.setObjectName("cbtonCheckBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbtonCheckBox)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cbtbbComboBox = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.cbtbbComboBox.setObjectName("cbtbbComboBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbtbbComboBox)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cbttbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.cbttbpDoubleSpinBox.setObjectName("cbttbpDoubleSpinBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbttbpDoubleSpinBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 160, 311, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 281, 111))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cbiEnabledCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.cbiEnabledCheckBox.setText("")
        self.cbiEnabledCheckBox.setObjectName("cbiEnabledCheckBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbiEnabledCheckBox)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cbiBurstIntervaloubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.cbiBurstIntervaloubleSpinBox.setMinimum(0.0)
        self.cbiBurstIntervaloubleSpinBox.setMaximum(86400.0)
        self.cbiBurstIntervaloubleSpinBox.setObjectName("cbiBurstIntervaloubleSpinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbiBurstIntervaloubleSpinBox)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBox.setMaximum(5000)
        self.spinBox.setSingleStep(128)
        self.spinBox.setProperty("value", 2048)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.groupBox = QtWidgets.QGroupBox(Subsystem)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 311, 321))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cwponCheckBox = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.cwponCheckBox.setText("")
        self.cwponCheckBox.setObjectName("cwponCheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cwponCheckBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cwpblDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpblDoubleSpinBox.setSingleStep(0.25)
        self.cwpblDoubleSpinBox.setProperty("value", 0.5)
        self.cwpblDoubleSpinBox.setObjectName("cwpblDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cwpblDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cwpbsDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpbsDoubleSpinBox.setMinimum(0.01)
        self.cwpbsDoubleSpinBox.setMaximum(200.0)
        self.cwpbsDoubleSpinBox.setSingleStep(0.1)
        self.cwpbsDoubleSpinBox.setProperty("value", 1.0)
        self.cwpbsDoubleSpinBox.setObjectName("cwpbsDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cwpbsDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cwpbnSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cwpbnSpinBox.setMinimum(1)
        self.cwpbnSpinBox.setMaximum(200)
        self.cwpbnSpinBox.setProperty("value", 30)
        self.cwpbnSpinBox.setObjectName("cwpbnSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cwpbnSpinBox)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cwpbbDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwpbbDoubleSpinBox.setSingleStep(0.1)
        self.cwpbbDoubleSpinBox.setProperty("value", 0.5)
        self.cwpbbDoubleSpinBox.setObjectName("cwpbbDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cwpbbDoubleSpinBox)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.cwpbbComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cwpbbComboBox.setObjectName("cwpbbComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cwpbbComboBox)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cwppSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.cwppSpinBox.setMaximum(500)
        self.cwppSpinBox.setProperty("value", 1)
        self.cwppSpinBox.setObjectName("cwppSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cwppSpinBox)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cwptbpDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.cwptbpDoubleSpinBox.setSingleStep(0.1)
        self.cwptbpDoubleSpinBox.setProperty("value", 0.1)
        self.cwptbpDoubleSpinBox.setObjectName("cwptbpDoubleSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cwptbpDoubleSpinBox)
        self.formLayoutWidget.raise_()
        self.groupBox_2.raise_()
        self.groupBox_2.raise_()
        self.groupBox_2.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4 = QtWidgets.QGroupBox(Subsystem)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 631, 80))
        self.groupBox_4.setObjectName("groupBox_4")

        self.retranslateUi(Subsystem)
        QtCore.QMetaObject.connectSlotsByName(Subsystem)

    def retranslateUi(self, Subsystem):
        _translate = QtCore.QCoreApplication.translate
        Subsystem.setWindowTitle(_translate("Subsystem", "MainWindow"))
        self.groupBox_2.setTitle(_translate("Subsystem", "Bottom Track"))
        self.label_9.setText(_translate("Subsystem", "CBTON"))
        self.label_10.setText(_translate("Subsystem", "CBTBB"))
        self.label_11.setText(_translate("Subsystem", "CBTTBP"))
        self.groupBox_3.setTitle(_translate("Subsystem", "Burst Mode"))
        self.label_12.setText(_translate("Subsystem", "Burst Mode ON"))
        self.label_13.setText(_translate("Subsystem", "Burst Interval"))
        self.label_14.setText(_translate("Subsystem", "Number of Ensembles"))
        self.groupBox.setTitle(_translate("Subsystem", "Water Profile"))
        self.label.setText(_translate("Subsystem", "CWPON"))
        self.label_2.setText(_translate("Subsystem", "CWPBL (m)"))
        self.label_3.setText(_translate("Subsystem", "CWPBS (m)"))
        self.label_4.setText(_translate("Subsystem", "CWPBN"))
        self.label_5.setText(_translate("Subsystem", "CWPBB Lag Length (m)"))
        self.label_6.setText(_translate("Subsystem", "Pulse Type"))
        self.label_7.setText(_translate("Subsystem", "CWPP"))
        self.label_8.setText(_translate("Subsystem", "CWPTBP"))
        self.groupBox_4.setTitle(_translate("Subsystem", "Data Output"))

